### ISSUE TITLE
Name, Description, Company, etc.

### ISSUE THREAD

**Issue by darshanshankar** [evshiron/nwjs-builder#11]
Right now, nwjs-builder uses the default nwjs/Chromium copyright, original filename, product name, etc. I need to use Resource Hacker to rewrite those values to my own product. Ideally I wouldn't have to do that. Any plans to add that?

![image](https://cloud.githubusercontent.com/assets/8766412/15277230/cc2e7300-1ab2-11e6-8e30-1b8851d1f337.png)

On a separate note, any idea why I need to use side-by-side packaging now? In older versions of nwjs (0.12) I was able to build just fine using grunt-nw-builder and it would package my js/html into the nw.exe. However that doesn't work in 0.14.5 and your nwjs-builder. My app only loads if side-by-side is enabled. Could it be a path issue?

**Comment by evshiron** [comment]
The "Copyright" is affected by the line at https://github.com/evshiron/nwjs-builder/blob/master/lib/build/win32.js#L227. Currently it's set only when we have a `author` property in the `package.json`. If you want custom copyright string rather than `Copyright @ ${ author }`, let me know.
I was in the second issue as well, but it came out to be an issue with node.js 4.0.0, whose streaming is broken somewhere. node.js 4.1+ works just fine. Please try unzipping the combined `.exe` and see if the unzipping works without any errors. If error occurs and you are using node.js 4.0.0, upgrade it and try again. If it still fails, tell me your environment and I will have a look in it.

**Comment by darshanshankar** [comment]
Ah, ok the `author` property fixes the copyright which is fine for me.

The `Company` is still the default one for NW.js, and it appears on hover of the .exe. 

![image](https://cloud.githubusercontent.com/assets/8766412/15280011/d6690e70-1adf-11e6-82f8-f26fc3a78f34.png)

Shows up in Resource Hacker as the `CompanyName` field.

![image](https://cloud.githubusercontent.com/assets/8766412/15280025/02465782-1ae0-11e6-90ec-7f4ae048776c.png)

And for the second issue (side-by-side packaging), I'll take a look later tonight. FWIW, I'm on node 4.4.0.

**Comment by evshiron** [comment]
Glad to hear that. BTW `nwjs-builder` has just upgraded to 1.6.0, which accepts a `nwjsBuilder` property in the `package.json`, that should help you with the company name. See #12 for detail :)

**Comment by darshanshankar** [comment]
Ah that's perfect, exactly what I was looking for. Thanks!

**Comment by darshanshankar** [comment]
> Please try unzipping the combined .exe and see if the unzipping works without any errors.
By the way, I tried unzipping (on win10 x64) Getting a checksum error when using 7zip to unzip it. Any idea why that could be?

**Comment by evshiron** [comment]
@darshanshankar Thanks for the report. I will look into it. It might be better if you open another issue for it :)
