### ISSUE TITLE
use displayName as binary output name

### ISSUE THREAD

**Issue by conceptualspace** [evshiron/nwjs-builder#26]
currently, npm spec says that "name" property in package.json should be lowercase (https://docs.npmjs.com/files/package.json), but since this is used as the binary filename, our final output ends up as "name.exe" or "name.app" instead of "Name.exe" or "Name.app".

Ideally the binary would use the "displayName" property, which is case sensitive (this was the behaviour of the now deprecated nw-builder)

**Comment by evshiron** [comment]
Reasonable. I wasn't in it because as long as my applications would not be published on npmjs.com, the nonstandard `name` brings nothing more than a warning from `npm`.
I prefer `executableName` more than `displayName` because the former looks more accurate. I will add a `--executable-name` option later in this day.
If you have any ideas, let me know :)

**Comment by conceptualspace** [comment]
I'd be less inclined to add properties if the displayName essentially
captures the same distinction, but a comand line parameter would do the
trick too!

**Comment by evshiron** [comment]
Added in `nwjs-builder` 1.10.6.
