### ISSUE TITLE
Exclude specified files and sub-directories

### ISSUE THREAD

**Issue by BoatsAreRockable** [evshiron/nwjs-builder#36]
Similar to #33, it is possible to exclude particular files and sub-directories from being exported?

For instance my app has a docs folder and a README file - both of which do not need to be included in the output packages.

**Comment by evshiron** [comment]
I have discussed with the creator of that issue and decided not to implement it. For reasoning you might want to read the "For feature requests" section of README.
`nwjs-builder` is not going to be an all-in-one module and I think it's worthless to implement it because it's not a core-related feature and some other code in your building pipeline will do it much better and provide more flexiblility over an integration into `nwjs-builder`.
I hope I have explained it well and as always, feel free to ask if you have further questions.

**Comment by BoatsAreRockable** [comment]
Thanks for the clarity. I appreciate it must be frustrating repeatingly recieving issues like this!
