### ISSUE TITLE
Reading and writing files

### ISSUE THREAD

**Issue by alexandre1985** [evshiron/nwjs-builder#56]
I have an nw app that reads and writes files to "./_file_"
The reading and writing seems to be working ok, but when I close and open the aplication it doesn't read the last modification of the file.
What can be done?
(I have only tested on windows x64 and it didn't work).
I would like a solution that works on all platforms.
Thank you

**Comment by evshiron** [comment]
Greetings,

If you pack your nw.js application into `.nw` (and combine it to the executable), when getting launched it will be unzipped into a temporary directory which will be its `cwd` afterwards. It's a mechanism that nw.js uses.

To solve this problem:

* Use `--side-by-side` option of `nwjs-builder` for no packaging so that there is no unzipping or `cwd` change any more,
* or call `process.chdir(path.dirname(process.execPath))` at the beginning of your logic to fix the `cwd`.

BTW relative paths are always related to the `cwd`.

**Comment by alexandre1985** [comment]
Thank you @evshiron :)
I have made my path to store data of my program using the module ospath and everytime it runs it will fetch and store the files on the same path. Thanks
